name: Build and Publish OpenWrt Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses-dev zlib1g-dev gawk wget git gettext libssl-dev xsltproc rsync unzip python3 python3-distutils zstd

      - name: Download and extract OpenWrt Image Builder
        run: |
          wget https://downloads.openwrt.org/releases/24.10-SNAPSHOT/targets/ath79/generic/openwrt-imagebuilder-24.10-SNAPSHOT-ath79-generic.Linux-x86_64.tar.zst
          tar -xvf openwrt-imagebuilder-*.tar.zst

      - name: Build OpenWrt Image
        run: |
          cd openwrt-imagebuilder-24.10-SNAPSHOT-ath79-generic.Linux-x86_64/
          make image  \
          PROFILE="dlink_dir-842-c2" \
          PACKAGES="luci" \
          FILES="files" \
          DISABLED_SERVICES=""

      - name: Create GitHub Release
        id: create_release
        run: |
          TAG_NAME="v1.0.0"
          RELEASE_NAME="OpenWrt Image v1.0.0"
          BODY="This release contains the OpenWrt image for the dlink_dir-842-c2 profile."
          curl -X POST \
            -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" \
            -d "{\"tag_name\": \"$TAG_NAME\", \"name\": \"$RELEASE_NAME\", \"body\": \"$BODY\", \"draft\": false, \"prerelease\": false}" \
            https://api.github.com/repos/${{github.repository}}/releases


      - name: Upload Image to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          files: /home/runner/work/OpenWrt-Builder/OpenWrt-Builder/openwrt-imagebuilder-24.10-SNAPSHOT-ath79-generic.Linux-x86_64/bin/targets/ath79/generic/*.bin
          tag: v1.0.0
